name: display_metrics_windows
description: Windows implementation of display_metrics
repository: https://github.com/nukeolay/display_metrics
version: 1.0.0

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  display_metrics_platform_interface:
    path: ../display_metrics_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    implements: display_metrics
    platforms:
      windows:
        dartPluginClass: DisplayMetricsWindows
        pluginClass: DisplayMetricsWindowsPluginCApi

topics:
  - screen
  - ppi
  - size
  - resolution
  - pixels  